// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    title: string;
    description?: (string | null);
    color?: (string | null);
};

export type CategoryPublic = {
    title: string;
    description?: (string | null);
    color?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type CategoryUpdate = {
    title?: (string | null);
    description?: (string | null);
    color?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic message.
 */
export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type RepeatType = 'none' | 'on_completion' | 'on_due_date';

export type TaskCompletionPublic = {
    id: string;
    task_id: string;
    completed_at: string;
};

export type TaskCompletionsPublic = {
    data: Array<TaskCompletionWithTask>;
    count: number;
};

export type TaskCompletionUpdate = {
    completed_at: string;
};

export type TaskCompletionWithTask = {
    id: string;
    task_id: string;
    completed_at: string;
    task_title: string;
};

export type TaskCreate = {
    title: string;
    description?: (string | null);
    category_id?: (string | null);
    color?: (string | null);
    start_date?: (string | null);
    due_date?: (string | null);
    repeat_type?: RepeatType;
    repeat_seconds?: number;
    repeat_minutes?: number;
    repeat_hours?: number;
    repeat_days?: number;
    repeat_weeks?: number;
    repeat_months?: number;
    repeat_years?: number;
};

export type TaskPublic = {
    title: string;
    description?: (string | null);
    category_id?: (string | null);
    color?: (string | null);
    start_date?: (string | null);
    due_date?: (string | null);
    repeat_type?: RepeatType;
    repeat_seconds?: number;
    repeat_minutes?: number;
    repeat_hours?: number;
    repeat_days?: number;
    repeat_weeks?: number;
    repeat_months?: number;
    repeat_years?: number;
    id: string;
    owner_id: string;
    completed?: boolean;
    created_at?: (string | null);
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
    category_id?: (string | null);
    color?: (string | null);
    start_date?: (string | null);
    due_date?: (string | null);
    repeat_type?: RepeatType;
    repeat_seconds?: number;
    repeat_minutes?: number;
    repeat_hours?: number;
    repeat_days?: number;
    repeat_weeks?: number;
    repeat_months?: number;
    repeat_years?: number;
    completed?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    categoryId: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    categoryId: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type TasksReadTasksData = {
    limit?: number;
    skip?: number;
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadAllCompletionsData = {
    limit?: number;
    skip?: number;
};

export type TasksReadAllCompletionsResponse = (TaskCompletionsPublic);

export type TasksDeleteCompletionData = {
    completionId: string;
};

export type TasksDeleteCompletionResponse = (Message);

export type TasksUpdateCompletionData = {
    completionId: string;
    requestBody: TaskCompletionUpdate;
};

export type TasksUpdateCompletionResponse = (TaskCompletionPublic);

export type TasksReadTaskData = {
    taskId: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (Message);

export type TasksCompleteTaskData = {
    taskId: string;
};

export type TasksCompleteTaskResponse = (TaskPublic);

export type TasksReadTaskCompletionsData = {
    taskId: string;
};

export type TasksReadTaskCompletionsResponse = (Array<TaskCompletionPublic>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);