"""remove_is_superuser_from_user

Revision ID: f6f4759ce76c
Revises: 1915418a220c
Create Date: 2026-03-23 03:07:24.745930

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6f4759ce76c'
down_revision = '1915418a220c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
