"""add_category_and_task_category_id

Revision ID: 3d4592c885ec
Revises: fe56fa70289e
Create Date: 2026-03-22 10:04:49.793202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d4592c885ec'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskcompletion')
    op.drop_table('pushsubscription')
    op.drop_index(op.f('ix_reminder_remind_at_sent'), table_name='reminder')
    op.drop_table('reminder')
    op.add_column('category', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('category', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('category', 'color')
    op.drop_column('category', 'name')
    op.drop_constraint(op.f('task_parent_id_fkey'), 'task', type_='foreignkey')
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'repeat_months')
    op.drop_column('task', 'repeat_weeks')
    op.drop_column('task', 'repeat_seconds')
    op.drop_column('task', 'repeat_hours')
    op.drop_column('task', 'repeat_type')
    op.drop_column('task', 'parent_id')
    op.drop_column('task', 'repeat_days')
    op.drop_column('task', 'repeat_years')
    op.drop_column('task', 'start_date')
    op.drop_column('task', 'repeat_minutes')
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('repeat_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('repeat_years', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('repeat_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('repeat_type', postgresql.ENUM('NONE', 'ON_COMPLETION_DATE', 'ON_DUE_DATE', name='repeattype'), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('repeat_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('repeat_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('repeat_weeks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('repeat_months', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('task_parent_id_fkey'), 'task', 'task', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('category', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('color', sa.VARCHAR(length=19), autoincrement=False, nullable=False))
    op.drop_column('category', 'description')
    op.drop_column('category', 'title')
    op.create_table('reminder',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', postgresql.ENUM('BEFORE_DUE', 'AT_START', 'CUSTOM', 'RECURRING_NUDGE', name='remindertype'), autoincrement=False, nullable=False),
    sa.Column('offset_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nudge_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remind_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('reminder_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reminder_pkey'))
    )
    op.create_index(op.f('ix_reminder_remind_at_sent'), 'reminder', ['remind_at', 'sent'], unique=False)
    op.create_table('pushsubscription',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('p256dh', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('auth', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('pushsubscription_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pushsubscription_pkey'))
    )
    op.create_table('taskcompletion',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('taskcompletion_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('taskcompletion_pkey'))
    )
    # ### end Alembic commands ###
