"""Added colors

Revision ID: f48a06c40da3
Revises: f6f4759ce76c
Create Date: 2026-05-21 18:19:41.076079

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f48a06c40da3'
down_revision = 'f6f4759ce76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('task', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'color')
    op.drop_column('category', 'color')
    # ### end Alembic commands ###
