"""add_task_dates_and_recurrence

Revision ID: 3bc58765c6b7
Revises: 3d4592c885ec
Create Date: 2026-03-22 10:41:28.808998

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3bc58765c6b7'
down_revision = '3d4592c885ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task', sa.Column('repeat_type', sa.VARCHAR(length=20), nullable=False, server_default='none'))
    op.add_column('task', sa.Column('repeat_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_hours', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_weeks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_months', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_years', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task', sa.Column('repeat_original_start_day', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('repeat_original_due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'repeat_original_due_day')
    op.drop_column('task', 'repeat_original_start_day')
    op.drop_column('task', 'repeat_years')
    op.drop_column('task', 'repeat_months')
    op.drop_column('task', 'repeat_weeks')
    op.drop_column('task', 'repeat_days')
    op.drop_column('task', 'repeat_hours')
    op.drop_column('task', 'repeat_minutes')
    op.drop_column('task', 'repeat_seconds')
    op.drop_column('task', 'repeat_type')
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'start_date')
    # ### end Alembic commands ###
